version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Mount the initdb directory
  renia-tg-bot:
    restart: always
    environment:
      TG_TOKEN: "token2"
    build: ./bot
    volumes:
      - ./logs:/logs
      - ./photos:/photos

  renia-tg-backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres

