version: '3.8'

volumes:
  postgresql:

services:
  postgres:
    image: postgres:16.2@sha256:0df4feaa20162e5659ca29f073a72f0e519611a59e91283b4dd4dceba390a43b
    container_name: my-postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d

  renia-tg-bot:
    restart: always
    environment:
      TG_TOKEN: ${TG_TOKEN}
    build: ./bot
    volumes:
      - ./logs:/var/log/renia
      - ./photos:/var/lib/photos

  renia-tg-backend:
    build: ./backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - postgres

