#use local image as base
FROM bot-renia:latest

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt /app/requirements.txt

COPY . /app
RUN chmod +x /app/start_server.sh

RUN apt-get update && \
    apt-get upgrade -y && \
    pip install --upgrade -r /app/requirements.txt --use-pep517 --use-feature=fast-deps

COPY . /app

# Expose the port the application runs on
EXPOSE 5001

ENTRYPOINT ["./start_server.sh"]
