# Use the official Python image as the base image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the container
COPY . /app
RUN chmod +x /app/start_server.sh

# Install dependencies
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install --no-cache-dir -r ./requirements.txt --no-cache-dir && \
    apk --purge del .build-deps

# Expose the port the application runs on
EXPOSE 5001

ENTRYPOINT ["./start_server.sh"]