# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /main

# Copy the application files to the container
COPY . /main

# Install dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

# Command to run the application
CMD ["python", "main.py"]
